trigger:
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md

strategy:
  matrix:
    Node6:
      nodejs_version: '6'
    Node8:
      nodejs_version: '8'
  maxParallel: 2

pool:
  vmImage: 'vs2017-win2016'

variables:
  CI: true

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodejs_version)
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Build'

  - task: PublishTestResults@2
    displayName: Publish Tests Results
    inputs:
      testResultsFiles: 'results-*.xml'
      testResultsFormat: XUnit
      searchFolder: '$(Build.SourcesDirectory)'
    condition: succeededOrFailed()
